[pytest]
asyncio_mode = auto
filterwarnings = 
    ignore:PydanticDeprecatedSince20:DeprecationWarning
    ignore:MovedIn20Warning:DeprecationWarning
    ignore:is_categorical_dtype is deprecated:DeprecationWarning

markers =
    ingestor: mark tests related to ingestor workflows

