name: Contract Tests
on:
  pull_request:
    paths: ["api-contracts/openapi.yaml", "apps/**", "services/**"]
  push:
    branches: [main]

jobs:
  schemathesis:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup Python
        uses: actions/setup-python@v5
        with: { python-version: '3.11' }
      - name: Install dependencies
        run: pip install -r requirements.txt
      - name: Start API server
        run: |
          uvicorn cms_pricing.main:app --host 0.0.0.0 --port 8000 &
          sleep 10
      - name: Install schemathesis
        run: pip install schemathesis
      - name: Run schemathesis
        run: schemathesis run api-contracts/openapi.yaml --base-url=http://localhost:8000
  pytest:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup Python
        uses: actions/setup-python@v5
        with: { python-version: '3.11' }
      - name: Install deps
        run: pip install -r requirements.txt
      - name: Run contract unit tests
        run: pytest -q
